from backpack.extensions.backprop_extension import BackpropExtension
from torch.nn import (
    ELU,
    SELU,
    AvgPool1d,
    AvgPool2d,
    AvgPool3d,
    Conv1d,
    Conv2d,
    Conv3d,
    ConvTranspose1d,
    ConvTranspose2d,
    ConvTranspose3d,
    CrossEntropyLoss,
    NLLLoss,
    Dropout,
    Flatten,
    LeakyReLU,
    Linear,
    LogSigmoid,
    MaxPool1d,
    MaxPool2d,
    MaxPool3d,
    MSELoss,
    ReLU,
    Sigmoid,
    Tanh,
    ZeroPad2d,
    LogSoftmax,
    Softmax,
)

from . import (
    activations,
    conv1d,
    conv2d,
    conv3d,
    convtranspose1d,
    convtranspose2d,
    convtranspose3d,
    dropout,
    flatten,
    linear,
    losses,
    pooling,
)

from optim_landscape.artificial_landscapes import RastriginLoss, RosenbrockLoss


class HesScale(BackpropExtension):
    def __init__(self, savefield="hesscale"):
        super().__init__(
            savefield=savefield,
            fail_mode="ERROR",
            module_exts={
                MSELoss: losses.MSELossHesScale(),
                NLLLoss: losses.NLLLossHesScale(),
                CrossEntropyLoss: losses.CrossEntropyLossHesScale(),
                RastriginLoss: losses.RastriginLossHesScale(),
                RosenbrockLoss: losses.RosenbrockLossHesScale(),
                Linear: linear.LinearHesScale(),
                MaxPool1d: pooling.HesScaleMaxPool1d(),
                AvgPool1d: pooling.HesScaleAvgPool1d(),
                MaxPool2d: pooling.HesScaleMaxPool2d(),
                AvgPool2d: pooling.HesScaleAvgPool2d(),
                MaxPool3d: pooling.HesScaleMaxPool3d(),
                AvgPool3d: pooling.HesScaleAvgPool3d(),
                Conv1d: conv1d.HesScaleConv1d(),
                Conv2d: conv2d.HesScaleConv2d(),
                Conv3d: conv3d.HesScaleConv3d(),
                ConvTranspose1d: convtranspose1d.HesScaleConvTranspose1d(),
                ConvTranspose2d: convtranspose2d.HesScaleConvTranspose2d(),
                ConvTranspose3d: convtranspose3d.HesScaleConvTranspose3d(),
                Dropout: dropout.HesScaleDropout(),
                Flatten: flatten.HesScaleFlatten(),
                ReLU: activations.ReLUHesScale(),
                Sigmoid: activations.SigmoidHesScale(),
                Tanh: activations.TanhHesScale(),
                LeakyReLU: activations.LeakyReLUHesScale(),
                LogSigmoid: activations.LogSigmoidHesScale(),
                ELU: activations.ELUHesScale(),
                SELU: activations.SELUHesScale(),
                LogSoftmax: activations.LogSoftmaxHesScale(),
                Softmax: activations.SoftmaxHesScale(),
            },
        )
